### ISSUE TITLE
KeyError: '$defs' when using nested $defs

### ISSUE THREAD

**Issue by dbeniteza** [mnboos/jsonschema-default#13]
Hello,

I'm having some issues when using nested $defs to generate the defaults for the jsonschema.
Here it is a sample json schema with nested $defs ( _street_ object within _address_ object):

```json
{
    "$id": "https://example.com/schemas/customer",
  
    "type": "object",
    "properties": {
      "first_name": { "type": "string", "default": "Default NAME value"},
      "last_name": { "type": "string", "default": "Default LAST NAME value" },
      "address": { "$ref": "#/$defs/address" }
    },
    "required": ["first_name", "last_name", "address"],
  
    "$defs": {
      "address": {
        "additionalProperties": false,
        "type": "object",
        "required": [
            "street"
        ],
        "properties": {
          "street": {
            "$ref": "#/$defs/street"
          }
        }
      },
      "street": { 
        "additionalProperties": false,
        "type": "object",
        "required": [
          "name",
          "block"
        ],
        "properties": {
          "name": {
            "type": "string",
            "default": "Default STREET NAME value"
          },
          "block": {
            "type": "number",
            "default": 123
          }
        }
      }
    }
  }
```

To test this schema, I use a dummy python script that loads the schema as a dict from a file. See the resulting error below:
```
root@58e73c593a93:/workspace-local# python3 default_json.py
Traceback (most recent call last):
  File "/workspace-local/default_json.py", line 62, in <module>
    sys.exit(main())
  File "/workspace-local/default_json.py", line 53, in main
    default_dev = jsonschema_default.create_from(data)
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 28, in create_from
    obj = {p: _get_default(name=p, prop=prop, schema=schema) for p, prop in properties.items()}
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 28, in <dictcomp>
    obj = {p: _get_default(name=p, prop=prop, schema=schema) for p, prop in properties.items()}
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 67, in _get_default
    default = _create_ref(name=ref, schema=schema)
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 159, in _create_ref
    return create_from(ref_schema)
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 28, in create_from
    obj = {p: _get_default(name=p, prop=prop, schema=schema) for p, prop in properties.items()}
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 28, in <dictcomp>
    obj = {p: _get_default(name=p, prop=prop, schema=schema) for p, prop in properties.items()}
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 67, in _get_default
    default = _create_ref(name=ref, schema=schema)
  File "/usr/local/lib/python3.9/site-packages/jsonschema_default/__init__.py", line 157, in _create_ref
    elem = elem[path_parth]
KeyError: '$defs'
```

**Comment by mnboos** [comment]
This is now fixed in [release 1.6.0](https://pypi.org/project/jsonschema-default/1.6.0/)
