### ISSUE TITLE
ValueError: not enough values to unpack - $ref to other schemas

### ISSUE THREAD

**Issue by dbeniteza** [mnboos/jsonschema-default#14]
Hello,

Taking the two following schemas, _/schemas/customer_ and _/schemas/address_ as example:
```json
{
  "$id": "https://example.com/schemas/customer",

  "type": "object",
  "properties": {
    "first_name": { "$ref": "#/$defs/name" },
    "last_name": { "$ref": "#/$defs/name" },
    "shipping_address": { "$ref": "/schemas/address" },
    "billing_address": { "$ref": "/schemas/address" }
  },
  "required": ["first_name", "last_name", "shipping_address"],

  "$defs": {
    "name": { "type": "string" }
  }
}
```

```json
{
    "$id": "https://example.com/schemas/address",
  
    "type": "object",
    "properties": {
      "street_address":
        {
          "$anchor": "street_address",
          "type": "string"
        },
      "city": { "type": "string" },
      "state": { "type": "string" }
    },
    "required": ["street_address", "city", "state"]
  }
```

When creating the defaults from the _/schemas/customer_ schema, which has some $refs to _/schemas/address_, results in the following error:
```
root@789f1de62c83:/workspace-local# python default_json.py
Traceback (most recent call last):
  File "/workspace-local/default_json.py", line 58, in <module>
    sys.exit(main())
  File "/workspace-local/default_json.py", line 49, in main
    default_dev = jsonschema_default.create_from(schema_path)
  File "/usr/local/lib/python3.10/site-packages/jsonschema_default/__init__.py", line 7, in create_from
    return main.JsonSchemaDefault(schema, parent=None).generate()
  File "/usr/local/lib/python3.10/site-packages/jsonschema_default/main.py", line 148, in generate
    result = self._object()
  File "/usr/local/lib/python3.10/site-packages/jsonschema_default/main.py", line 80, in _object
    default[name] = JsonSchemaDefault(schema, parent=self).generate()
  File "/usr/local/lib/python3.10/site-packages/jsonschema_default/main.py", line 121, in generate
    return self.ref(ref)
  File "/usr/local/lib/python3.10/site-packages/jsonschema_default/main.py", line 94, in ref
    file, path = ref.split("#")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by dbeniteza** [comment]
I took the examples from [Structuring a complex schema - $ref](https://json-schema.org/understanding-json-schema/structuring.html#id18).
I've created the 2 schema files, /schemas/customer.json and /schemas/address.json in a linux container.
Since $refs are supposed to by URI-reference, how jsonschema-default search/check for the $refs? Does it download the schemas pointed in $ref? Does it search for the schemas at file system level?

Another question, `jsonschema_default.create_from` methods receives the schema as a parameter only accepted in 3 types (dict, str or Path), so in my customer case where they have a HTTP repository with the schemas. Does that imply that the only way to create the defaults (with create_from) is by downloading the schema to validate? Not allowing a URL as parameter for the create_from doesn't let you more options than downloading or having the schema locally in order to load into a dict/str or referencing it through a Path.

**Comment by mnboos** [comment]
Currently, loading schemas from the web is not supported, as you requested in #15. However, I plan to implement this.
